# netlify.toml — SmokeWins

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# Nopein tapa: ohita Netlifyn post processing kokonaan
[build.processing]
  skip_processing = true

# Turva- ja selaimen headerit
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; script-src 'self'; style-src 'self' 'unsafe-inline'; connect-src 'self';"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Pitkä välimuisti brändikuville (esim. logo)
[[headers]]
  for = "/branding/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Pitkä välimuisti fonteille
[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Varmistetaan, että /guides toimii ilman 404:ää
[[redirects]]
  from = "/guides"
  to = "/guides/"
  status = 301
  force = true
