[build]
command = "npm run build"
publish = "dist"

# Optional: If you prefer TOML redirects instead of public/_redirects
# [[redirects]]
# from = "/go/*"
# to = "https://example.com/:splat"
# status = 302
# force = true
